### ISSUE TITLE
Create simple form mechanism to delete questions

### ISSUE THREAD

**Issue by LordGarod** [costezki/lifecost-ui#15]
When the question is deleted, you need to consider the rest of the collection, so that other users also deleted the question.

**Comment by costezki** [comment]
* If there are no answers then delete the question
* If there are answers to the question then the question is NEVER deleted but Deprecated!

* An archived/deprecated question cannot be seen by any user but the Admin unless it has already answered the question at least once
* Admin can un-archive/publish a question and thus make it normal or visible/published


Status types: 
-> Draft (just created) 
-> Published (after the publish button is pressed) 
-> Deprecated (if the question is deleted, and it can become published again)
